### ISSUE TITLE
Broke with 2022.7 HA

### ISSUE THREAD

**Issue by talondnb** [boralyl/kodi-recently-added#13]
This addon seems to have broken with 2022.7.x HA that was just realeased.

Is there any plans to update/fix?

**Comment by boralyl** [comment]
I haven't updated to the latest version yet, could you provide any errors or logs?

**Comment by talondnb** [comment]
Apologies for the lack of info.

So the main issue is Lovelace doesn't appear to detect the cards anymore. The integration via HACS/HA looks OK and the sensors are there. The upcoming-media-card just doesn't appear.

![Screen Shot 2022-07-10 at 09 02 52](https://user-images.githubusercontent.com/3942363/178127426-6921cc20-70eb-414e-82f5-fa080837ccb4.png)

Unfortunately I'm not sure where exactly to look for logs here. I've checked HA core logs but nothing appears there.

**Comment by boralyl** [comment]
This doesn't seem like an issue with the sensor since it's pulling in data.  I also verified this component is working in the latest version. I know the author of the upcoming-media-card has stopped supporting that card and it is archived.  Can you verify it's still installed properly?  You may have to manually do it now that it may not be able to be installed via HACS.

Unfortunately I can' help much with that particular error as it's related to a custom card.

**Comment by talondnb** [comment]
Ahh sorry I thought this integration also provided the card as it was documented that way. No worries I will close this off, thanks!
